### ISSUE TITLE
能在react-native中使用吗？有相关文档吗？

### ISSUE THREAD

**Issue by 1111mp** [JackJiang2011/MobileIMSDK#11]
能在react-native中使用吗？有相关文档吗？

**Comment by JackJiang2011** [comment]
这是原生代码编写，应该不能在rn中直接用

**Comment by SuperKoier** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。
