### ISSUE TITLE
服务器连接不稳定时会出现这个异常

### ISSUE THREAD

**Issue by hope320** [JackJiang2011/MobileIMSDK#13]
![image](https://user-images.githubusercontent.com/24400386/53395856-e4c23800-39dd-11e9-8ccd-28076a867ef4.png)

**Comment by JackJiang2011** [comment]
你用 [最新版本](https://github.com/JackJiang2011/MobileIMSDK/releases/tag/3.3.1b181124(v3.3.2))，就不会有这个问题了。

**Comment by hope320** [comment]
好的，谢谢大佬
