### ISSUE TITLE
Android启动App进入首页就会ANR

### ISSUE THREAD

**Issue by jy7758258** [JackJiang2011/MobileIMSDK#23]
Pixel2（Android 系统版本11），Pixel5（Android 系统版本13），还有一个Oppo（Android 系统版本13）的手机启动App进入首页就会ANR

**Comment by SuperKoier** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by SuperKoier** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。
