### ISSUE TITLE
依赖没发布到仓库吗

### ISSUE THREAD

**Issue by GXSZone** [JackJiang2011/MobileIMSDK#31]

**Comment by SuperKoier** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by JackJiang2011** [comment]
是的，直接用jar吧。端太多，版本也经常更新，我就懒得上传maven去折腾了。抱歉

**Comment by SuperKoier** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。
