### ISSUE TITLE
转成Android Studio版的工程源码就好了

### ISSUE THREAD

**Issue by tianshaokai** [JackJiang2011/MobileIMSDK#7]
eclipse 都不好导入

**Comment by JackJiang2011** [comment]
你可以新建一个空的Android Studio工程，把res、src、androidmanifaset.xml文件复制进去就行了。
其实我这边有完整的Android Studio 3.0环境，但考虑到AS又是翻墙、又是gradle这些乱七八糟的，把开发环境的门槛搞的太高，所以暂时还是保持简单的Eclipse环境了。

如果在转AS的过程中遇到任何问题，可以到论坛发贴：http://www.52im.net/forum-89-1.html，我可以提供例子，分分钟解决问题。
